### ISSUE TITLE
DDoS on the Miner

### ISSUE THREAD

**Issue by MaxHillebrand** [pool2win/braidpool#18]
This is a really fascinating paper - thanks for doing this research!! 

---

Chapter 5.8 covers the DDoS protection for the Hub. The solution is that the Hub initiates communication to the miner's onion server. Yes, this should reduce DDoS pressure on the Hub.

But does it open DDoS vectors against all miners? Since the shares and miners onion's are public, it seems to me that an attacker can now DDoS any miners endpoint, and potentially block communication to the Hub.

I am probably missing something here, but it seems that the DDoS issue is not solved, just moved to another party...

**Comment by pool2win** [comment]
Thanks @MaxHillebrand for your kind words.

Tor's v3 hidden services provide DDoS protection mechanisms (*). If the service uses 'enough' introduction points and sets the parameters DoS params appropriately. Essentially this means that we could require the hub to run tor v3 hidden service and life would be fine. Equivalently, miners can protect themselves by using tor's v3 hidden services, especially if they set their DoS burst per second parameter (**) to really low.

For some more context, when I was toying with using I2P, I had reversed the requirement to run hidden services on to miners  and I stuck with it because I like that it provides yet another possibility to keep the hub "away from the limelight" :)

(*) Section 5  (Rendezvous Points and hidden services) https://svn-archive.torproject.org/svn/projects/design-paper/tor-design.html
(**) https://gitweb.torproject.org/torspec.git/tree/rend-spec-v3.txt#n1582.

**Comment by MaxHillebrand** [comment]
> If the service uses 'enough' introduction points

That's very interesting, thanks for the linked references.

**Comment by Rikj000** [comment]
@pool2win since [Tor itself has been facing a lot of DDoS issues lately](https://status.torproject.org/issues/2022-06-09-network-ddos/),   
did you consider switching the Tor implementation of this project to I2P? :thinking:
